# Kubernetes Service definition to expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: movie-application-backend-service
  labels:
    app: movie-application-backend
spec:
  type: NodePort
  selector:
    app: movie-application-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080