# .github/workflows/dev_pipeline.yml

name: 1. Dev Pipeline

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  # --------------------------------------------------------
  # JOB 1: Validate Build
  # --------------------------------------------------------
  dev-validation:
    runs-on: ubuntu-latest
    name: Validate Build (1/2)
    steps:
      - name: Checkout code (1/4)
        uses: actions/checkout@v4
        
      - name: Set up JDK 21 (2/4)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Grant Execute Permission to Maven Wrapper (3/4)
        working-directory: movie-application-backend
        run: chmod +x mvnw
        
      - name: Validate Maven Build (4/4)
        working-directory: movie-application-backend
        run: ./mvnw validate

  # --------------------------------------------------------
  # JOB 2: Promote to Test
  # --------------------------------------------------------
  push-to-test:
    runs-on: ubuntu-latest
    needs: dev-validation
    name: Promote to Test (2/2)
    
    steps:
      - name: Checkout code (dev) (1/3)
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.CI_TRIGGER_TOKEN }}

      - name: Configure Git (2/3)
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Promote to test (3/3)
        working-directory: movie-application-backend 
        run: |
          echo "Promoting changes from 'dev' to 'test' branch..."
        
          git fetch origin

          git checkout -b test origin/test

          git merge -X theirs origin/dev --no-ff --allow-unrelated-histories -m "Merge dev into test for promotion"
          
          git push origin test
