# .github/workflows/test_pipeline.yml

name: 2. Test Pipeline

on:
  push:
    branches:
      - test

jobs:
  # --------------------------------------------------------
  # JOB 1: Run All Unit Tests
  # --------------------------------------------------------
  all-tests:
    runs-on: ubuntu-latest
    name: Run All Tests (1/2)
    
    steps:
      - name: Checkout code (1/4)
        uses: actions/checkout@v4

      - name: Set up JDK 21 (2/4)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant Execute Permission to Maven Wrapper (3/4)
        working-directory: movie-application-backend
        run: chmod +x mvnw

      - name: Run All Tests (4/4)
        working-directory: movie-application-backend
        run: ./mvnw clean verify

  # --------------------------------------------------------
  # JOB 2: Promotion to Staging
  # --------------------------------------------------------
  push-to-staging:
    runs-on: ubuntu-latest
    needs: all-tests
    name: Promotion to Staging (2/2)
    
    steps:
      - name: Checkout code (test) (1/3)
        uses: actions/checkout@v4
        with:
          ref: test
          token: ${{ secrets.CI_TRIGGER_TOKEN }}

      - name: Configure Git (2/3)
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Promote to Staging (3/3)
        run: |
          echo "Promoting changes from 'test' to 'staging' branch..."

          git fetch origin

          git checkout -b staging origin/staging

          git merge -X theirs origin/test --no-ff --allow-unrelated-histories -m "Merge test into staging for promotion"
          
          git push origin staging
